### PR TITLE
refactor: Remove Enterprise Catalog API V1

### PR DESCRIPTION
**Pull request by ruzniaievdm**
Replace [usage](https://github.com/openedx/frontend-app-admin-portal/blob/master/src/data/services/LmsApiService.js#L254-L256) with corresponding to the enterprise-catalog service

YT: https://youtrack.raccoongang.com/issue/OeX_Depr-263

### CODE REVIEW

**Review by idegtiarov — CHANGES_REQUESTED** [review]
Thanks, since we've changed the API should some tests be updated as well?

**Review by dyudyunov — APPROVED** [review]

**Comment by ruzniaievdm** [comment]
> Thanks, since we've changed the API should some tests be updated as well?

Those changes that I made were not covered by tests
If needed i can write

**Comment by idegtiarov** [comment]
Got it, lets's check the coverage then.

**Review by idegtiarov — APPROVED** [review]

**Review by idegtiarov — APPROVED** [review]
LGTM!

**Pull request closed without merging**
